### ISSUE TITLE
LocalPlayer() override error

### ISSUE THREAD

**Issue by ForrestMarkX** [Kefta/gs_lib#3]
Your override to LocalPlayer() will sometimes error out because Entity(1) isn't always the local player, or a valid player either

**Comment by Kefta** [comment]
That's for serverside only. LocalPlayer doesn't only exist on the client

**Comment by Kefta** [comment]
Shit, never mind. Found the issue.

**Comment by Kefta** [comment]
Fixed, should've been loaded serverside instead of shared
